import localFont from "next/font/local";
import type { Metadata } from "next";
import "@/globals.css";
import Navbar from "@/shared/component/layout/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// FONT CONFIGURATION
// const customFont = localFont({
// THIS CAN BE AN ARRAY TOO, CHECK NEXT DOCS
// src: "./",
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ADD THIS CLASS TO HTML ELEMENT FOR ADDING THE FONT className={customFont.className}
    <html lang="en">
      <body>
        <main>
          <Navbar
            title="NAVBAR"
            items={[
              { linkURL: "/about", title: "about" },
              {
                parent: "parent",
                children: [{ linkURL: "/about", title: "about in parent" }],
              },
            ]}
          />
          {children}
          <h1>FOOTER IS NEEDED</h1>
        </main>
      </body>
    </html>
  );
}
