import localFont from "next/font/local";
import type { Metadata } from "next";
import "@/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// FONT CONFIGURATION
// const customFont = localFont({
// THIS CAN BE AN ARRAY TOO, CHECK NEXT DOCS
// src: "./",
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ADD THIS CLASS TO HTML ELEMENT FOR ADDING THE FONT className={customFont.className}
    <html lang="en">
      <body>
        <main>
          <h1>NAVBAR IS NEEDED</h1>
          {children}
          <h1>FOOTER IS NEEDED</h1>
        </main>
      </body>
    </html>
  );
}
